train: ../data/DOTA/yolo_formatted_images/train
val:  ../data/DOTA/yolo_formatted_images/validation
test: ../data/DOTA/yolo_formatted_images/test

# number of classes
nc: 18

# class names
names: [
    "plane", 
    "ship", 
    "storage-tank", 
    "baseball-diamond", 
    "tennis-court", 
    "basketball-court", 
    "ground-track-field", 
    "harbor", 
    "bridge", 
    "large-vehicle",
    "small-vehicle",
    "helicopter",
    "roundabout",
    "soccer-ball-field", 
    "swimming-pool",
    "container-crane",
    "airport",
    "helipad"]