train: training_data/road_sign/images/train/ 
val:  training_data/road_sign/images/validation/
test: training_data/road_sign/images/test/

# number of classes
nc: 4

# class names
names: ["trafficlight","stop", "speedlimit","crosswalk"]